apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      retention: 24h
      externalLabels:
        source_cluster: crossplane1
      remoteWrite:
        - url: "https://prometheus.example.com/api/v1/write"
          writeRelabelConfigs:
            - sourceLabels: [__name__]
              regex: "crossplane:.*|apiserver_storage_objects|container_memory_working_set_bytes|container_cpu_usage_seconds_total|etcd_request_duration_seconds.*|apiserver_request_duration_seconds.*|apiserver_current_inflight_requests|apiserver_request_total|apiserver_flowcontrol_.*|node_memory_.*|node_cpu_seconds_total"
              action: keep
